# ─────────────────────────────────────────────────────────
#  quiz_bank.py  –  Sinhala Commerce Quiz Questions
#  Add / edit questions freely. Keep the same dict structure.
# ─────────────────────────────────────────────────────────

QUIZZES = [

    # ── ගිණුම්කරණය (Accounting) ──────────────────────────
    {
        "id": 1,
        "question": "දෙපැත්ත ගිණුම් ක්‍රමයේ මූලික සමීකරණය කුමක්ද?",
        "options": [
            "වත්කම් = බැරකම් + ප්‍රාග්ධනය",
            "ආදායම = වියදම් + ලාභ",
            "ලාභ = ආදායම - වත්කම්",
            "ප්‍රාග්ධනය = බැරකම් - වත්කම්",
        ],
        "correct_option_id": 0,
        "explanation": "Assets = Liabilities + Capital — මෙය ගිණුම්කරණ සමීකරණයයි.",
    },
    {
        "id": 2,
        "question": "Trial Balance (අත්හදා ශේෂ) සකස් කරන්නේ කුමන අරමුණින්ද?",
        "options": [
            "ලාභ ගණනය කිරීමට",
            "ගිණුම් ගොපිතා නිවැරදිද යන්න සොයා ගැනීමට",
            "ව්‍යාපාරයේ වත්කම් ලැයිස්තු කිරීමට",
            "බදු ගණනය කිරීමට",
        ],
        "correct_option_id": 1,
        "explanation": "Trial Balance මඟින් Debit සහ Credit දෙදෙනාම සමතුලිතද යන්න පරීක්ෂා කෙරේ.",
    },
    {
        "id": 3,
        "question": "Depreciation (ක්ෂයවීම) ගිණුම් ගත කරන්නේ කුමන මූලධර්මය යටතේද?",
        "options": [
            "Revenue Recognition",
            "Matching Principle",
            "Going Concern",
            "Materiality",
        ],
        "correct_option_id": 1,
        "explanation": "Matching Principle — ආදායමට සහ වියදමට අදාල කාල සීමා ගැළපිය යුතුය.",
    },
    {
        "id": 4,
        "question": "Cash Book හි Contra Entry යනු කුමක්ද?",
        "options": [
            "බැංකුවෙන් මුදල් ආපසු ගැනීම",
            "Cash සහ Bank තීරු දෙකෙහිම ඇතුළත් කිරීමක්",
            "ණය ගැනීම",
            "වත්කමක් විකිණීම",
        ],
        "correct_option_id": 1,
        "explanation": "Contra Entry — Cash සහ Bank columns දෙකෙහිම (Debit + Credit) ඇතුළත් වේ.",
    },
    {
        "id": 5,
        "question": "BRS (Bank Reconciliation Statement) හදන ප්‍රධාන හේතුව කුමක්ද?",
        "options": [
            "බදු ගෙවීමට",
            "Cash Book හා Pass Book අතර වෙනස් හේතු සොයා ගැනීමට",
            "ලාභ ගිනි ගැනීමට",
            "නව ගිණුම් ආරම්භ කිරීමට",
        ],
        "correct_option_id": 1,
        "explanation": "BRS — Cash Book Balance සහ Bank Statement Balance සංසන්දනය කොට වෙනස්කම් සොයා ගනී.",
    },

    # ── ව්‍යාපාර අධ්‍යයනය (Business Studies) ────────────
    {
        "id": 6,
        "question": "Sole Proprietorship (තනිකඩ ව්‍යාපාරය) හි ප්‍රධාන අවාසිය කුමක්ද?",
        "options": [
            "ලාභ බෙදා ගැනීම",
            "සීමා රහිත වගකීම",
            "බදු ගෙවීම",
            "ප්‍රාග්ධනය ඉහළ වීම",
        ],
        "correct_option_id": 1,
        "explanation": "Unlimited Liability — හිමිකරු පෞද්ගලික දේපල ද ණය ගෙවීමට ඉදිරිපත් කළ යුතුය.",
    },
    {
        "id": 7,
        "question": "Marketing Mix හි '4P' වලට ඇතුළත් නොවන්නේ?",
        "options": ["Product", "Price", "People", "Place"],
        "correct_option_id": 2,
        "explanation": "4P = Product, Price, Place, Promotion. 'People' 7P හි ඇතුළත් ය, 4P හි නොවේ.",
    },
    {
        "id": 8,
        "question": "GDP (Gross Domestic Product) ගණනය කිරීමේ ද්‍රව්‍ය ක්‍රමය (Expenditure Method) ගණනය ක්‍රමය කුමක්ද?",
        "options": [
            "GDP = C + I + G + (X - M)",
            "GDP = ආදායම + ලාභ",
            "GDP = ස්ථිර වත්කම් + ගෙවුම්",
            "GDP = නිෂ්පාදනය × මිල",
        ],
        "correct_option_id": 0,
        "explanation": "GDP = C (Consumption) + I (Investment) + G (Government) + Net Exports.",
    },
    {
        "id": 9,
        "question": "Partnership (හවුල් ව්‍යාපාරය) ක්‍රියාත්මක කළ හැකි උපරිම සාමාජිකයින් ගණන කීයද?",
        "options": ["10", "20", "50", "100"],
        "correct_option_id": 1,
        "explanation": "සාමාන්‍ය හවුල් ව්‍යාපාරවල සාමාජිකයින් 20 දක්වා සීමා කෙරේ (බැංකු 10 ද).",
    },
    {
        "id": 10,
        "question": "Consumer Protection Act ශ්‍රී ලංකාවේ කල්‍යාණය ආරක්ෂා කරන ගනුදෙනුකරුවන් ආයතනය කොයිද?",
        "options": ["SLTB", "CAA", "SEC", "BOI"],
        "correct_option_id": 1,
        "explanation": "CAA — Consumer Affairs Authority ශ්‍රී ලංකාවේ පාරිභෝගිකයින් ආරක්ෂා කරයි.",
    },

    # ── ආර්ථික විද්‍යාව (Economics) ─────────────────────
    {
        "id": 11,
        "question": "ඉල්ලුම් නියමය (Law of Demand) පවසන්නේ කුමක්ද?",
        "options": [
            "මිල ඉහළ යත්ම ඉල්ලුම ද ඉහළ යයි",
            "මිල ඉහළ යත්ම ඉල්ලුම අඩු වෙයි",
            "ඉල්ලුම සහ සැපයුම සෑම විටම සමානය",
            "ආදායම ඉහළ යත්ම ඉල්ලුම අඩු වෙයි",
        ],
        "correct_option_id": 1,
        "explanation": "Law of Demand: Price ↑ → Quantity Demanded ↓ (inverse relationship).",
    },
    {
        "id": 12,
        "question": "Inflation (උද්ධමනය) මනිනු ලබන ශ්‍රී ලංකා ප්‍රධාන දර්ශකය කුමක්ද?",
        "options": ["GDP Deflator", "CCPI", "WPI", "PPI"],
        "correct_option_id": 1,
        "explanation": "CCPI — Colombo Consumer Price Index ශ්‍රී ලංකාවේ ප්‍රධාන උද්ධමන දර්ශකයයි.",
    },
    {
        "id": 13,
        "question": "Opportunity Cost (අවස්ථා වියදම) යනු කුමක්ද?",
        "options": [
            "ව්‍යාපාරයේ ඇති සම්පූර්ණ වියදම",
            "විකල්ප තේරීමකින් අත්හැරෙන හොඳම ප්‍රතිලාභය",
            "ලාභ ප්‍රමාණය",
            "නිෂ්පාදන වියදම",
        ],
        "correct_option_id": 1,
        "explanation": "Opportunity Cost = Next best alternative foregone — ආර්ථික විද්‍යාවේ ප්‍රධාන සංකල්පය.",
    },
    {
        "id": 14,
        "question": "Perfect Competition (සම්පූර්ණ තරගකාරිත්වය) හි ලක්ෂණයක් නොවන්නේ?",
        "options": [
            "ගැනුම්කරුවන් සහ විකුණුම්කරුවන් බොහෝ",
            "ඒකජාතික නිෂ්පාදන",
            "Price Maker",
            "නිදහස් ප්‍රවේශය",
        ],
        "correct_option_id": 2,
        "explanation": "Perfect Competition හි firms Price Takers. Price Makers වන්නේ Monopoly හිදී.",
    },
    {
        "id": 15,
        "question": "ශ්‍රී ලංකාවේ මධ්‍යම බැංකුව (Central Bank) ස්ථාපිත වූ වර්ෂය?",
        "options": ["1948", "1950", "1956", "1960"],
        "correct_option_id": 1,
        "explanation": "Central Bank of Sri Lanka 1950 අගෝස්තු 28 දින ස්ථාපිත විය.",
    },

    # ── Additional mixed questions ────────────────────────
    {
        "id": 16,
        "question": "Fixed Cost (ස්ථාවර වියදම) ලක්ෂණය කුමක්ද?",
        "options": [
            "නිෂ්පාදනය සමඟ වෙනස් වෙයි",
            "නිෂ්පාදනය කොයිතරම් වුණත් නොවෙනස්ව පවතී",
            "ශ්‍රමිකයින් ගෙවීම",
            "අමු ද්‍රව්‍ය වියදම",
        ],
        "correct_option_id": 1,
        "explanation": "Fixed Costs (කුලිය, රක්ෂණය) නිෂ්පාදන ප්‍රමාණය කෙසේ වෙතත් නොවෙනස්ව පවතී.",
    },
    {
        "id": 17,
        "question": "Balance of Trade (වෙළඳ ශේෂය) ලැබෙන්නේ කෙසේද?",
        "options": [
            "ආනයන - අපනයන",
            "අපනයන - ආනයන",
            "GDP - GNP",
            "ආදායම - වියදම",
        ],
        "correct_option_id": 1,
        "explanation": "Balance of Trade = Exports − Imports. Positive = Surplus, Negative = Deficit.",
    },
    {
        "id": 18,
        "question": "Debit Note (ඩෙබිට් සටහන) යවන්නේ කවුරුන්ද?",
        "options": ["විකුණුම්කරු", "ගැනුම්කරු", "බැංකුව", "රජය"],
        "correct_option_id": 1,
        "explanation": "Debit Note යවන්නේ ගැනුම්කරු (Buyer) — ආපසු ලබාදෙන භාණ්ඩ සඳහා.",
    },
    {
        "id": 19,
        "question": "Petty Cash Book ආරම්භ කළ හැකි ක්‍රමය?",
        "options": [
            "Simple System",
            "Imprest System",
            "Double Entry System",
            "Single Entry System",
        ],
        "correct_option_id": 1,
        "explanation": "Imprest System — ස්ථාවර මුදලක් (float) ආරම්භයේ ලබා, කාල සීමා අවසානයේ නැවත සම්පූර්ণ කෙරේ.",
    },
    {
        "id": 20,
        "question": "Fiscal Policy (මූල්‍ය ප්‍රතිපත්තිය) ක්‍රියාත්මක කරන ආයතනය?",
        "options": [
            "මධ්‍යම බැංකුව",
            "රජය (Ministry of Finance)",
            "IMF",
            "World Bank",
        ],
        "correct_option_id": 1,
        "explanation": "Fiscal Policy — රජය මගින් බදු හා රාජ්‍ය වියදම් හරහා ක්‍රියාත්මක කෙරේ.",
    },
    # ── Additional Quiz Set (21–40) ──────────────────────────

{
    "id": 21,
    "question": "Ledger (ප්‍රධාන පොත) යනු කුමක්ද?",
    "options": [
        "දිනපතා ගනුදෙනු ලියා තැබීම",
        "ගිණුම් වර්ගීකරණය කරන පොත",
        "බැංකු වාර්තාව",
        "බදු ලේඛනය",
    ],
    "correct_option_id": 1,
    "explanation": "Ledger — ගනුදෙනු ගිණුම් අනුව වර්ගීකරණය කර තැබේ.",
},
{
    "id": 22,
    "question": "Capital Expenditure (ප්‍රාග්ධන වියදම) උදාහරණයක් කුමක්ද?",
    "options": [
        "වැටුප් ගෙවීම",
        "විදුලි බිල්",
        "යන්ත්‍ර මිලදී ගැනීම",
        "කුලිය ගෙවීම",
    ],
    "correct_option_id": 2,
    "explanation": "Capital Expenditure — දිගු කාලීන වත්කම් මිලදී ගැනීම.",
},
{
    "id": 23,
    "question": "Entrepreneur (ව්‍යවසායකයා) හි ප්‍රධාන භූමිකාව කුමක්ද?",
    "options": [
        "වැටුප් ලබා ගැනීම",
        "අවදානම භාර ගැනීම",
        "බදු ගෙවීම",
        "නිෂ්පාදනය පාලනය නොකිරීම",
    ],
    "correct_option_id": 1,
    "explanation": "Entrepreneur — risk bearer (අවදානම භාරගන්නා පුද්ගලයා).",
},
{
    "id": 24,
    "question": "Demand Curve සාමාන්‍යයෙන් කෙසේ වේද?",
    "options": [
        "ඉහළට යන",
        "පහළට යන",
        "සෘජු රේඛාව",
        "වක්‍ර නැත",
    ],
    "correct_option_id": 1,
    "explanation": "Demand Curve downward sloping — මිල ↑ → ඉල්ලුම ↓.",
},
{
    "id": 25,
    "question": "CPU හි සම්පූර්ණ නාමය කුමක්ද?",
    "options": [
        "Central Processing Unit",
        "Computer Personal Unit",
        "Central Program Unit",
        "Control Processing Unit",
    ],
    "correct_option_id": 0,
    "explanation": "CPU = Central Processing Unit.",
},
{
    "id": 26,
    "question": "Journal Entry (දිනපතා සටහන) හි ප්‍රධාන අරමුණ කුමක්ද?",
    "options": [
        "ගිණුම් වර්ගීකරණය",
        "මුල් ගනුදෙනු ලියා තැබීම",
        "ලාභ ගණනය",
        "බැංකු පරීක්ෂාව",
    ],
    "correct_option_id": 1,
    "explanation": "Journal — original entry book.",
},
{
    "id": 27,
    "question": "Business Environment යනු කුමක්ද?",
    "options": [
        "ව්‍යාපාර ගොඩනැගිල්ල",
        "ව්‍යාපාරයට බලපාන බාහිර සහ අභ්‍යන්තර සාධක",
        "සේවකයන්",
        "ගිණුම් පද්ධතිය",
    ],
    "correct_option_id": 1,
    "explanation": "Business Environment includes internal & external factors.",
},
{
    "id": 28,
    "question": "Scarcity (හිඟතාව) යනු කුමක්ද?",
    "options": [
        "අවශ්‍යතා නොමැතිවීම",
        "සම්පත් සීමිත වීම",
        "ලාභ අඩුවීම",
        "වියදම් වැඩිවීම",
    ],
    "correct_option_id": 1,
    "explanation": "Scarcity — resources are limited, wants unlimited.",
},
{
    "id": 29,
    "question": "RAM හි කාර්යය කුමක්ද?",
    "options": [
        "දත්ත ස්ථිරව ගබඩා කිරීම",
        "තාවකාලික මතකය ලෙස භාවිතා වීම",
        "වීඩියෝ පෙන්වීම",
        "ප්‍රින්ට් කිරීම",
    ],
    "correct_option_id": 1,
    "explanation": "RAM — temporary memory.",
},
{
    "id": 30,
    "question": "Net Profit ගණනය කිරීමේ සූත්‍රය කුමක්ද?",
    "options": [
        "Gross Profit - Expenses",
        "Sales - Purchases",
        "Assets - Liabilities",
        "Income + Expenses",
    ],
    "correct_option_id": 0,
    "explanation": "Net Profit = Gross Profit - Expenses.",
},
{
    "id": 31,
    "question": "Management හි ප්‍රධාන කාර්යයක් නොවන්නේ?",
    "options": [
        "Planning",
        "Organizing",
        "Sleeping",
        "Controlling",
    ],
    "correct_option_id": 2,
    "explanation": "Management functions: Planning, Organizing, Leading, Controlling.",
},
{
    "id": 32,
    "question": "Elastic Demand යනු කුමක්ද?",
    "options": [
        "මිල වෙනස්වීමකට ඉල්ලුම වෙනස් නොවීම",
        "මිල වෙනස්වීමකට ඉල්ලුම වැඩි ලෙස වෙනස් වීම",
        "ස්ථාවර ඉල්ලුම",
        "අඩු ඉල්ලුම",
    ],
    "correct_option_id": 1,
    "explanation": "Elastic demand — high responsiveness.",
},
{
    "id": 33,
    "question": "Input Device එකක් නොවන්නේ කුමක්ද?",
    "options": [
        "Keyboard",
        "Mouse",
        "Monitor",
        "Scanner",
    ],
    "correct_option_id": 2,
    "explanation": "Monitor is an output device.",
},
{
    "id": 34,
    "question": "Drawings (හිමිකරු විසින් ගන්නා මුදල්) යනු කුමක්ද?",
    "options": [
        "ව්‍යාපාර ආදායම",
        "හිමිකරු විසින් භාවිතා කරන මුදල්",
        "බැංකු ණය",
        "ලාභය",
    ],
    "correct_option_id": 1,
    "explanation": "Drawings reduce capital.",
},
{
    "id": 35,
    "question": "SWOT Analysis හි 'S' යනු කුමක්ද?",
    "options": [
        "Sales",
        "Strengths",
        "System",
        "Strategy",
    ],
    "correct_option_id": 1,
    "explanation": "SWOT = Strengths, Weaknesses, Opportunities, Threats.",
},
{
    "id": 36,
    "question": "Monopoly යනු කුමක්ද?",
    "options": [
        "බොහෝ විකුණුම්කරුවන්",
        "එක් විකුණුම්කරුවෙක් පමණක්",
        "සමාන වෙළඳපොළ",
        "නිදහස් වෙළඳපොළ",
    ],
    "correct_option_id": 1,
    "explanation": "Monopoly — single seller.",
},
{
    "id": 37,
    "question": "Software යනු කුමක්ද?",
    "options": [
        "භෞතික උපාංග",
        "කම්පියුටර් වැඩසටහන්",
        "කේබල්",
        "පරිගණක කොටස්",
    ],
    "correct_option_id": 1,
    "explanation": "Software = programs.",
},
{
    "id": 38,
    "question": "Bad Debts යනු කුමක්ද?",
    "options": [
        "ගෙවිය යුතු ණය",
        "අපසු ලබාගත නොහැකි ණය",
        "ලාභය",
        "ආදායම",
    ],
    "correct_option_id": 1,
    "explanation": "Bad debts — irrecoverable debts.",
},
{
    "id": 39,
    "question": "Leadership style එකක් නොවන්නේ?",
    "options": [
        "Autocratic",
        "Democratic",
        "Laissez-faire",
        "Accounting",
    ],
    "correct_option_id": 3,
    "explanation": "Accounting is not a leadership style.",
},
{
    "id": 40,
    "question": "Internet යනු කුමක්ද?",
    "options": [
        "තනි පරිගණකයක්",
        "ගෝලීය ජාලයක එකතුව",
        "Software එකක්",
        "Hard disk එකක්",
    ],
    "correct_option_id": 1,
    "explanation": "Internet — global network.",
},
    {
    "id": 41,
    "question": "Purchases (මිලදී ගැනීම්) යනු කුමක්ද?",
    "options": [
        "භාණ්ඩ විකිණීම",
        "භාණ්ඩ මිලදී ගැනීම",
        "ලාභය",
        "වියදම",
    ],
    "correct_option_id": 1,
    "explanation": "Purchases යනු භාණ්ඩ මිලදී ගැනීමයි.",
},
{
    "id": 42,
    "question": "Expenses (වියදම්) යනු කුමක්ද?",
    "options": [
        "ආදායම",
        "ලාභය",
        "ව්‍යාපාරය පවත්වා ගැනීමට වැයවන මුදල්",
        "වත්කම්",
    ],
    "correct_option_id": 2,
    "explanation": "Expenses යනු ව්‍යාපාරය පවත්වා ගැනීමට වැයවන මුදල් වේ.",
},
{
    "id": 43,
    "question": "Owner’s Equity (හිමිකරුගේ ප්‍රාග්ධනය) යනු කුමක්ද?",
    "options": [
        "ව්‍යාපාර ණය",
        "ව්‍යාපාරයේ හිමිකරුට අයත් කොටස",
        "වියදම",
        "ලාභය",
    ],
    "correct_option_id": 1,
    "explanation": "Equity යනු හිමිකරුට අයත් වත්කම් කොටසයි.",
},
{
    "id": 44,
    "question": "Service business එකක් යනු කුමක්ද?",
    "options": [
        "භාණ්ඩ විකිණීම",
        "සේවාවක් ලබා දීම",
        "කර්මාන්තයක්",
        "ගොවිතැන",
    ],
    "correct_option_id": 1,
    "explanation": "Service business සේවාවන් ලබා දෙයි.",
},
{
    "id": 45,
    "question": "Customer (ගනුදෙනුකරු) යනු කවුද?",
    "options": [
        "ව්‍යාපාර හිමිකරු",
        "භාණ්ඩ හෝ සේවාවන් මිලදී ගන්නා පුද්ගලයා",
        "සේවකයා",
        "ගුරුවරයා",
    ],
    "correct_option_id": 1,
    "explanation": "Customer යනු භාණ්ඩ/සේවා මිලදී ගන්නා පුද්ගලයායි.",
},
{
    "id": 46,
    "question": "Need (අවශ්‍යතාව) යනු කුමක්ද?",
    "options": [
        "අවශ්‍ය නොවන දේ",
        "ජීවිතයට අත්‍යවශ්‍ය දේ",
        "ලාභය",
        "වියදම",
    ],
    "correct_option_id": 1,
    "explanation": "Needs යනු ජීවිතයට අත්‍යවශ්‍ය දේ වේ.",
},
{
    "id": 47,
    "question": "Wants (කැමැත්ත) යනු කුමක්ද?",
    "options": [
        "අත්‍යවශ්‍ය දේ",
        "අවශ්‍ය නොවන නමුත් කැමති දේ",
        "ලාභය",
        "වියදම",
    ],
    "correct_option_id": 1,
    "explanation": "Wants යනු අත්‍යවශ්‍ය නොවන නමුත් කැමති දේ වේ.",
},
{
    "id": 48,
    "question": "Goods (භාණ්ඩ) යනු කුමක්ද?",
    "options": [
        "සේවාවන්",
        "ස්පර්ශ කළ හැකි දේ",
        "ලාභය",
        "ආදායම",
    ],
    "correct_option_id": 1,
    "explanation": "Goods tangible items වේ.",
},
{
    "id": 49,
    "question": "Services (සේවාවන්) යනු කුමක්ද?",
    "options": [
        "ස්පර්ශ කළ හැකි දේ",
        "ස්පර්ශ කළ නොහැකි සේවාවන්",
        "වියදම",
        "ලාභය",
    ],
    "correct_option_id": 1,
    "explanation": "Services intangible වේ.",
},
{
    "id": 50,
    "question": "Mouse එක භාවිතා කරන්නේ කුමක් සඳහාද?",
    "options": [
        "දත්ත ඇතුළත් කිරීම",
        "තෝරා ගැනීම හා ක්ලික් කිරීම",
        "ප්‍රින්ට් කිරීම",
        "ගබඩා කිරීම",
    ],
    "correct_option_id": 1,
    "explanation": "Mouse pointing device එකකි.",
},
{
    "id": 51,
    "question": "Printer එක කුමන device එකක්ද?",
    "options": [
        "Input",
        "Output",
        "Storage",
        "Processing",
    ],
    "correct_option_id": 1,
    "explanation": "Printer is an output device.",
},
{
    "id": 52,
    "question": "Income (ආදායම) යනු කුමක්ද?",
    "options": [
        "වියදම",
        "ලාභය",
        "ව්‍යාපාරයට ලැබෙන මුදල්",
        "බැරකම්",
    ],
    "correct_option_id": 2,
    "explanation": "Income යනු ව්‍යාපාරයට ලැබෙන මුදල් වේ.",
},
    {
    "id": 53,
    "question": "Assets (වත්කම්) යනු කුමක්ද?",
    "options": [
        "ව්‍යාපාරයේ ණය",
        "ව්‍යාපාරයට අයිති වටිනා දේපල",
        "වියදම්",
        "ලාභ",
    ],
    "correct_option_id": 1,
    "explanation": "Assets යනු ව්‍යාපාරයට අයිති වටිනා දේපලයි.",
},
{
    "id": 54,
    "question": "Liabilities (බැරකම්) යනු කුමක්ද?",
    "options": [
        "වත්කම්",
        "ලාභ",
        "ගෙවිය යුතු ණය",
        "ආදායම",
    ],
    "correct_option_id": 2,
    "explanation": "Liabilities යනු ව්‍යාපාරය ගෙවිය යුතු ණයයි.",
},
{
    "id": 55,
    "question": "Sales (විකුණුම්) යනු කුමක්ද?",
    "options": [
        "භාණ්ඩ මිලදී ගැනීම",
        "භාණ්ඩ විකිණීම",
        "වියදම්",
        "ලාභ",
    ],
    "correct_option_id": 1,
    "explanation": "Sales යනු භාණ්ඩ විකිණීමයි.",
},

# ── Business Studies (BS) ─────────────────────
{
    "id": 56,
    "question": "Business (ව්‍යාපාරය) යනු කුමක්ද?",
    "options": [
        "කැමති ක්‍රීඩාව",
        "ලාභ ලබා ගැනීම සඳහා ක්‍රියාකාරකම්",
        "අධ්‍යාපනය",
        "සංචාරය",
    ],
    "correct_option_id": 1,
    "explanation": "Business යනු ලාභ අරමුණින් සිදු කරන ක්‍රියාකාරකම් වේ.",
},
{
    "id": 57,
    "question": "Entrepreneur යනු කවුද?",
    "options": [
        "කම්කරුවා",
        "ව්‍යාපාර හිමිකරු",
        "ගුරුවරයා",
        "ගනුදෙනුකරුවා",
    ],
    "correct_option_id": 1,
    "explanation": "Entrepreneur යනු ව්‍යාපාර ආරම්භ කරන පුද්ගලයායි.",
},
{
    "id": 58,
    "question": "Profit (ලාභය) යනු කුමක්ද?",
    "options": [
        "ආදායම - වියදම්",
        "වියදම් - ආදායම",
        "වත්කම් + බැරකම්",
        "ආදායම × 2",
    ],
    "correct_option_id": 0,
    "explanation": "Profit = Income - Expenses.",
},

# ── Economics (Econ) ─────────────────────────
{
    "id": 59,
    "question": "Demand (ඉල්ලුම) යනු කුමක්ද?",
    "options": [
        "විකිණීම",
        "භාණ්ඩ මිලදී ගැනීමට කැමැත්ත",
        "නිෂ්පාදනය",
        "වියදම",
    ],
    "correct_option_id": 1,
    "explanation": "Demand යනු මිලදී ගැනීමට කැමැත්තයි.",
},
{
    "id": 60,
    "question": "Supply (සැපයුම) යනු කුමක්ද?",
    "options": [
        "වියදම",
        "ලාභය",
        "විකිණීමට ඇති භාණ්ඩ ප්‍රමාණය",
        "ආදායම",
    ],
    "correct_option_id": 2,
    "explanation": "Supply යනු වෙළඳපොළට සැපයෙන භාණ්ඩ ප්‍රමාණයයි.",
},
{
    "id": 61,
    "question": "Price (මිල) යනු කුමක්ද?",
    "options": [
        "භාණ්ඩයක වටිනාකම",
        "වියදම",
        "ලාභය",
        "ආදායම",
    ],
    "correct_option_id": 0,
    "explanation": "Price යනු භාණ්ඩයක වටිනාකමයි.",
},

# ── IT ───────────────────────────────────────
{
    "id": 62,
    "question": "Computer යනු කුමක්ද?",
    "options": [
        "ගණනය කිරීමට භාවිතා කරන යන්ත්‍රයක්",
        "කාර්යාලයක්",
        "ගෙදරක්",
        "පුස්තකාලයක්",
    ],
    "correct_option_id": 0,
    "explanation": "Computer යනු ගණනය කිරීමට භාවිතා කරන යන්ත්‍රයක්.",
},
{
    "id": 63,
    "question": "Keyboard එක භාවිතා කරන්නේ කුමක් සඳහාද?",
    "options": [
        "දත්ත ඇතුළත් කිරීම",
        "දත්ත ප්‍රදර්ශනය",
        "ප්‍රින්ට් කිරීම",
        "ගබඩා කිරීම",
    ],
    "correct_option_id": 0,
    "explanation": "Keyboard is an input device.",
},
{
    "id": 64,
    "question": "Monitor එක කුමන device එකක්ද?",
    "options": [
        "Input",
        "Output",
        "Storage",
        "Processing",
    ],
    "correct_option_id": 1,
    "explanation": "Monitor is an output device.",
},

]
